// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nebula.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nebula.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316014518_F0013_AddLineOfBusinessAndWorkflowSlaThresholds")]
    partial class F0013_AddLineOfBusinessAndWorkflowSlaThresholds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nebula.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_Accounts_Region");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.ActivityTimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventPayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ATE_EntityType_OccurredAt");

                    b.ToTable("ActivityTimelineEvents", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerTenantId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ManagedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MgaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("PrimaryProgramId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrokerTenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Brokers_BrokerTenantId")
                        .HasFilter("\"BrokerTenantId\" IS NOT NULL");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Brokers_LicenseNumber");

                    b.HasIndex("ManagedByUserId")
                        .HasDatabaseName("IX_Brokers_ManagedByUserId");

                    b.HasIndex("MgaId");

                    b.HasIndex("PrimaryProgramId");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("IX_Brokers_Status_IsDeleted");

                    b.ToTable("Brokers", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.BrokerRegion", b =>
                {
                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BrokerId", "Region");

                    b.HasIndex("Region", "BrokerId")
                        .HasDatabaseName("IX_BrokerRegions_Region_BrokerId");

                    b.ToTable("BrokerRegions", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BrokerId");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.MGA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MGAs", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ManagedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MgaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagedByUserId")
                        .HasDatabaseName("IX_Programs_ManagedByUserId");

                    b.HasIndex("MgaId");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.ReferenceRenewalStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ColorGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("ReferenceRenewalStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Created",
                            ColorGroup = "intake",
                            Description = "Renewal record created from expiring policy",
                            DisplayName = "Created",
                            DisplayOrder = (short)1,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Early",
                            ColorGroup = "intake",
                            Description = "In early renewal window (90-120 days out)",
                            DisplayName = "Early",
                            DisplayOrder = (short)2,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "DataReview",
                            ColorGroup = "triage",
                            Description = "Coverage and account data review before outreach",
                            DisplayName = "Data Review",
                            DisplayOrder = (short)3,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "OutreachStarted",
                            ColorGroup = "waiting",
                            Description = "Active broker/account outreach begun",
                            DisplayName = "Outreach Started",
                            DisplayOrder = (short)4,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "WaitingOnBroker",
                            ColorGroup = "waiting",
                            Description = "Awaiting broker response or required renewal information",
                            DisplayName = "Waiting on Broker",
                            DisplayOrder = (short)5,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "InReview",
                            ColorGroup = "review",
                            Description = "Under underwriter review for renewal terms",
                            DisplayName = "In Review",
                            DisplayOrder = (short)6,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Quoted",
                            ColorGroup = "decision",
                            Description = "Renewal quote issued",
                            DisplayName = "Quoted",
                            DisplayOrder = (short)7,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Negotiation",
                            ColorGroup = "decision",
                            Description = "Actively negotiating renewal terms",
                            DisplayName = "Negotiation",
                            DisplayOrder = (short)8,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "BindRequested",
                            ColorGroup = "decision",
                            Description = "Renewal bind requested",
                            DisplayName = "Bind Requested",
                            DisplayOrder = (short)9,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Bound",
                            ColorGroup = "won",
                            Description = "Policy renewed and bound",
                            DisplayName = "Bound",
                            DisplayOrder = (short)10,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "NotRenewed",
                            ColorGroup = "lost",
                            Description = "Renewal closed without binding",
                            DisplayName = "Not Renewed",
                            DisplayOrder = (short)11,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Lost",
                            ColorGroup = "lost",
                            Description = "Lost to competitor",
                            DisplayName = "Lost",
                            DisplayOrder = (short)12,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Lapsed",
                            ColorGroup = "lost",
                            Description = "Policy expired without renewal",
                            DisplayName = "Lapsed",
                            DisplayOrder = (short)13,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Withdrawn",
                            ColorGroup = "lost",
                            Description = "Renewal withdrawn by broker or insured",
                            DisplayName = "Withdrawn",
                            DisplayOrder = (short)14,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Expired",
                            ColorGroup = "lost",
                            Description = "Renewal workflow expired before completion",
                            DisplayName = "Expired",
                            DisplayOrder = (short)15,
                            IsTerminal = true
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.ReferenceSubmissionStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ColorGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("ReferenceSubmissionStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Received",
                            ColorGroup = "intake",
                            Description = "Initial state when submission is created",
                            DisplayName = "Received",
                            DisplayOrder = (short)1,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Triaging",
                            ColorGroup = "triage",
                            Description = "Initial triage and data validation",
                            DisplayName = "Triaging",
                            DisplayOrder = (short)2,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "WaitingOnBroker",
                            ColorGroup = "waiting",
                            Description = "Awaiting additional information from broker",
                            DisplayName = "Waiting on Broker",
                            DisplayOrder = (short)3,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "WaitingOnDocuments",
                            ColorGroup = "waiting",
                            Description = "Awaiting required underwriting documents",
                            DisplayName = "Waiting on Documents",
                            DisplayOrder = (short)4,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "ReadyForUWReview",
                            ColorGroup = "review",
                            Description = "All data received, queued for underwriter",
                            DisplayName = "Ready for UW Review",
                            DisplayOrder = (short)5,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "InReview",
                            ColorGroup = "review",
                            Description = "Under active underwriter review",
                            DisplayName = "In Review",
                            DisplayOrder = (short)6,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "QuotePreparation",
                            ColorGroup = "decision",
                            Description = "Preparing quote terms for broker",
                            DisplayName = "Quote Preparation",
                            DisplayOrder = (short)7,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Quoted",
                            ColorGroup = "decision",
                            Description = "Quote issued, awaiting broker response",
                            DisplayName = "Quoted",
                            DisplayOrder = (short)8,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "RequoteRequested",
                            ColorGroup = "decision",
                            Description = "Broker requested revised quote terms",
                            DisplayName = "Requote Requested",
                            DisplayOrder = (short)9,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "BindRequested",
                            ColorGroup = "decision",
                            Description = "Broker accepted quote, bind in progress",
                            DisplayName = "Bind Requested",
                            DisplayOrder = (short)10,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Binding",
                            ColorGroup = "decision",
                            Description = "Binding and issuance processing in progress",
                            DisplayName = "Binding",
                            DisplayOrder = (short)11,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Bound",
                            ColorGroup = "won",
                            Description = "Policy bound and issued",
                            DisplayName = "Bound",
                            DisplayOrder = (short)12,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Declined",
                            ColorGroup = "lost",
                            Description = "Submission declined by underwriter",
                            DisplayName = "Declined",
                            DisplayOrder = (short)13,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Withdrawn",
                            ColorGroup = "lost",
                            Description = "Broker or insured withdrew submission",
                            DisplayName = "Withdrawn",
                            DisplayOrder = (short)14,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "NotQuoted",
                            ColorGroup = "lost",
                            Description = "Submission closed without quote issued",
                            DisplayName = "Not Quoted",
                            DisplayOrder = (short)15,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Lost",
                            ColorGroup = "lost",
                            Description = "Opportunity lost to another market or strategy change",
                            DisplayName = "Lost",
                            DisplayOrder = (short)16,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Expired",
                            ColorGroup = "lost",
                            Description = "Submission expired before disposition completed",
                            DisplayName = "Expired",
                            DisplayOrder = (short)17,
                            IsTerminal = true
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.ReferenceTaskStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.HasKey("Code");

                    b.ToTable("ReferenceTaskStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Open",
                            DisplayName = "Open",
                            DisplayOrder = (short)1
                        },
                        new
                        {
                            Code = "InProgress",
                            DisplayName = "In Progress",
                            DisplayOrder = (short)2
                        },
                        new
                        {
                            Code = "Done",
                            DisplayName = "Done",
                            DisplayOrder = (short)3
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Renewal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Created");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LineOfBusiness")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("IX_Renewals_CurrentStatus");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("AssignedToUserId", "CurrentStatus")
                        .HasDatabaseName("IX_Renewals_AssignedToUserId_CurrentStatus");

                    b.HasIndex("RenewalDate", "CurrentStatus")
                        .HasDatabaseName("IX_Renewals_RenewalDate_Status");

                    b.ToTable("Renewals", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Received");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LineOfBusiness")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PremiumEstimate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("IX_Submissions_CurrentStatus");

                    b.HasIndex("ProgramId");

                    b.HasIndex("AssignedToUserId", "CurrentStatus")
                        .HasDatabaseName("IX_Submissions_AssignedToUserId_CurrentStatus");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LinkedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Normal");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DueDate", "Status")
                        .HasDatabaseName("IX_Tasks_DueDate_Status")
                        .HasFilter("\"IsDeleted\" = false AND \"Status\" != 'Done'");

                    b.HasIndex("LinkedEntityType", "LinkedEntityId")
                        .HasDatabaseName("IX_Tasks_LinkedEntity");

                    b.HasIndex("AssignedToUserId", "Status", "DueDate")
                        .HasDatabaseName("IX_Tasks_AssignedToUserId_Status_DueDate");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdpIssuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdpSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RegionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdpIssuer", "IdpSubject")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProfiles_IdpIssuer_IdpSubject");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.WorkflowSlaThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TargetDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WarningDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "Status")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowSlaThresholds_EntityType_Status");

                    b.ToTable("WorkflowSlaThresholds", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowSlaThresholds_WarningLessThanTarget", "\"WarningDays\" < \"TargetDays\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("1fef8cb4-2f9b-41e8-9329-3c1a5d22790a"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "Received",
                            TargetDays = 2,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 1
                        },
                        new
                        {
                            Id = new Guid("f6969f8b-7ab9-4ab0-a6e9-26f95f57b21c"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "Triaging",
                            TargetDays = 5,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 2
                        },
                        new
                        {
                            Id = new Guid("379f3ad6-68f0-4d2f-b52f-5ab9bb40f157"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "WaitingOnBroker",
                            TargetDays = 10,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 5
                        },
                        new
                        {
                            Id = new Guid("33cc5f8d-33ea-4f8a-a737-2f64946f044f"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "WaitingOnDocuments",
                            TargetDays = 10,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 5
                        },
                        new
                        {
                            Id = new Guid("ec690f3d-84c8-4709-8b32-ff1efde52e52"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "ReadyForUWReview",
                            TargetDays = 7,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 3
                        },
                        new
                        {
                            Id = new Guid("8b43ed42-17f2-426a-a14a-442f6a7d43d4"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "InReview",
                            TargetDays = 14,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 5
                        },
                        new
                        {
                            Id = new Guid("ecf8f24e-8ead-4a44-b123-b85b6527db31"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "QuotePreparation",
                            TargetDays = 7,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 3
                        },
                        new
                        {
                            Id = new Guid("3047cb13-59f8-4d87-a79d-e80e9dcf28ea"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "Quoted",
                            TargetDays = 21,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 7
                        },
                        new
                        {
                            Id = new Guid("95db58fe-ef54-4c7b-b707-0cdf6458cd5b"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "RequoteRequested",
                            TargetDays = 21,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 7
                        },
                        new
                        {
                            Id = new Guid("0ef57fce-6bd8-42e7-b1ef-767e44a02817"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "BindRequested",
                            TargetDays = 5,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 2
                        },
                        new
                        {
                            Id = new Guid("f419f936-3f6f-4135-9d9b-7744bb5e43b8"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "Binding",
                            TargetDays = 5,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 2
                        },
                        new
                        {
                            Id = new Guid("30efe68f-9e5c-4e7f-9191-e68ee0f8eb26"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "Created",
                            TargetDays = 3,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 1
                        },
                        new
                        {
                            Id = new Guid("0e5f31e6-af58-4e30-8ea0-f2d6f862994e"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "Early",
                            TargetDays = 30,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 7
                        },
                        new
                        {
                            Id = new Guid("f0f6f093-7e6e-45f5-ac84-76510ddfe371"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "DataReview",
                            TargetDays = 5,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 2
                        },
                        new
                        {
                            Id = new Guid("bb695667-05cf-43dd-a89c-c05e4747967c"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "OutreachStarted",
                            TargetDays = 7,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 3
                        },
                        new
                        {
                            Id = new Guid("2a620479-fc25-4a25-b0c5-1dce00a3693a"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "WaitingOnBroker",
                            TargetDays = 10,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 5
                        },
                        new
                        {
                            Id = new Guid("77ca3fa9-fddd-47ec-b4d2-84bcbf001687"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "InReview",
                            TargetDays = 14,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 5
                        },
                        new
                        {
                            Id = new Guid("f501f5dd-23d4-4250-9eab-65a70d0c08f5"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "Quoted",
                            TargetDays = 21,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 7
                        },
                        new
                        {
                            Id = new Guid("d7fe40cd-c9a5-4fd5-b09c-47f10ff0f20f"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "Negotiation",
                            TargetDays = 21,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 7
                        },
                        new
                        {
                            Id = new Guid("fdf17afe-4182-46e4-bf8b-3079e74b3579"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "BindRequested",
                            TargetDays = 5,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 2
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_WT_EntityId_OccurredAt");

                    b.ToTable("WorkflowTransitions", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Broker", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.MGA", "Mga")
                        .WithMany()
                        .HasForeignKey("MgaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nebula.Domain.Entities.Program", "PrimaryProgram")
                        .WithMany()
                        .HasForeignKey("PrimaryProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mga");

                    b.Navigation("PrimaryProgram");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.BrokerRegion", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany("BrokerRegions")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany("Contacts")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Program", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.MGA", "Mga")
                        .WithMany()
                        .HasForeignKey("MgaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mga");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Renewal", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Broker");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Submission", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Broker");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Broker", b =>
                {
                    b.Navigation("BrokerRegions");

                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
