// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nebula.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nebula.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nebula.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_Accounts_Region");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.ActivityTimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventPayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ATE_EntityType_OccurredAt");

                    b.ToTable("ActivityTimelineEvents", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerTenantId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ManagedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MgaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("PrimaryProgramId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrokerTenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Brokers_BrokerTenantId")
                        .HasFilter("\"BrokerTenantId\" IS NOT NULL");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Brokers_LicenseNumber");

                    b.HasIndex("ManagedByUserId")
                        .HasDatabaseName("IX_Brokers_ManagedByUserId");

                    b.HasIndex("MgaId");

                    b.HasIndex("PrimaryProgramId");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("IX_Brokers_Status_IsDeleted");

                    b.ToTable("Brokers", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.BrokerRegion", b =>
                {
                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BrokerId", "Region");

                    b.HasIndex("Region", "BrokerId")
                        .HasDatabaseName("IX_BrokerRegions_Region_BrokerId");

                    b.ToTable("BrokerRegions", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BrokerId");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.MGA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MGAs", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Carrier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LineOfBusiness")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Premium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("IX_Policies_ExpirationDate");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Policies_PolicyNumber");

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ManagedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MgaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagedByUserId")
                        .HasDatabaseName("IX_Programs_ManagedByUserId");

                    b.HasIndex("MgaId");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.ReferenceRenewalStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ColorGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("ReferenceRenewalStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Identified",
                            ColorGroup = "intake",
                            Description = "Renewal created from expiring policy; not yet worked",
                            DisplayName = "Identified",
                            DisplayOrder = (short)1,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Outreach",
                            ColorGroup = "waiting",
                            Description = "Distribution has initiated broker/account contact",
                            DisplayName = "Outreach",
                            DisplayOrder = (short)2,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "InReview",
                            ColorGroup = "review",
                            Description = "Underwriting is reviewing the renewal",
                            DisplayName = "In Review",
                            DisplayOrder = (short)3,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Quoted",
                            ColorGroup = "decision",
                            Description = "Quote has been prepared and shared",
                            DisplayName = "Quoted",
                            DisplayOrder = (short)4,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Completed",
                            ColorGroup = "won",
                            Description = "Renewal successfully bound; linked to a policy or submission",
                            DisplayName = "Completed",
                            DisplayOrder = (short)5,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Lost",
                            ColorGroup = "lost",
                            Description = "Renewal not retained",
                            DisplayName = "Lost",
                            DisplayOrder = (short)6,
                            IsTerminal = true
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.ReferenceSubmissionStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ColorGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("ReferenceSubmissionStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Received",
                            ColorGroup = "intake",
                            Description = "Initial state when submission is created",
                            DisplayName = "Received",
                            DisplayOrder = (short)1,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Triaging",
                            ColorGroup = "triage",
                            Description = "Initial triage and data validation",
                            DisplayName = "Triaging",
                            DisplayOrder = (short)2,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "WaitingOnBroker",
                            ColorGroup = "waiting",
                            Description = "Awaiting additional information from broker",
                            DisplayName = "Waiting on Broker",
                            DisplayOrder = (short)3,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "ReadyForUWReview",
                            ColorGroup = "review",
                            Description = "All data received, queued for underwriter",
                            DisplayName = "Ready for UW Review",
                            DisplayOrder = (short)4,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "InReview",
                            ColorGroup = "review",
                            Description = "Under active underwriter review",
                            DisplayName = "In Review",
                            DisplayOrder = (short)5,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Quoted",
                            ColorGroup = "decision",
                            Description = "Quote issued, awaiting broker response",
                            DisplayName = "Quoted",
                            DisplayOrder = (short)6,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "BindRequested",
                            ColorGroup = "decision",
                            Description = "Broker accepted quote, bind in progress",
                            DisplayName = "Bind Requested",
                            DisplayOrder = (short)7,
                            IsTerminal = false
                        },
                        new
                        {
                            Code = "Bound",
                            ColorGroup = "won",
                            Description = "Policy bound and issued",
                            DisplayName = "Bound",
                            DisplayOrder = (short)8,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Declined",
                            ColorGroup = "lost",
                            Description = "Submission declined by underwriter",
                            DisplayName = "Declined",
                            DisplayOrder = (short)9,
                            IsTerminal = true
                        },
                        new
                        {
                            Code = "Withdrawn",
                            ColorGroup = "lost",
                            Description = "Broker or insured withdrew submission",
                            DisplayName = "Withdrawn",
                            DisplayOrder = (short)10,
                            IsTerminal = true
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.ReferenceTaskStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.HasKey("Code");

                    b.ToTable("ReferenceTaskStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Open",
                            DisplayName = "Open",
                            DisplayOrder = (short)1
                        },
                        new
                        {
                            Code = "InProgress",
                            DisplayName = "In Progress",
                            DisplayOrder = (short)2
                        },
                        new
                        {
                            Code = "Done",
                            DisplayName = "Done",
                            DisplayOrder = (short)3
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Renewal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BoundPolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Identified");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LineOfBusiness")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LostReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LostReasonDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PolicyExpirationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RenewalSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("TargetOutreachDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Renewals_AccountId");

                    b.HasIndex("BoundPolicyId");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("IX_Renewals_BrokerId");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("IX_Renewals_CurrentStatus");

                    b.HasIndex("PolicyId")
                        .IsUnique()
                        .HasDatabaseName("IX_Renewals_PolicyId_Active")
                        .HasFilter("\"IsDeleted\" = false AND \"CurrentStatus\" NOT IN ('Completed', 'Lost')");

                    b.HasIndex("RenewalSubmissionId");

                    b.HasIndex("TargetOutreachDate")
                        .HasDatabaseName("IX_Renewals_TargetOutreachDate")
                        .HasFilter("\"IsDeleted\" = false AND \"CurrentStatus\" = 'Identified'");

                    b.HasIndex("AssignedToUserId", "CurrentStatus")
                        .HasDatabaseName("IX_Renewals_AssignedToUserId_CurrentStatus");

                    b.HasIndex("PolicyExpirationDate", "CurrentStatus")
                        .HasDatabaseName("IX_Renewals_PolicyExpirationDate_CurrentStatus");

                    b.ToTable("Renewals", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Received");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LineOfBusiness")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("PremiumEstimate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Submissions_AccountId");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("IX_Submissions_AssignedToUserId");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("IX_Submissions_BrokerId");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("IX_Submissions_CurrentStatus");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("IX_Submissions_EffectiveDate");

                    b.HasIndex("ProgramId");

                    b.HasIndex("AssignedToUserId", "CurrentStatus")
                        .HasDatabaseName("IX_Submissions_AssignedToUserId_CurrentStatus");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LinkedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Normal");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId", "AssignedToUserId")
                        .HasDatabaseName("IX_Tasks_CreatedByUserId_AssignedToUserId");

                    b.HasIndex("DueDate", "Status")
                        .HasDatabaseName("IX_Tasks_DueDate_Status")
                        .HasFilter("\"IsDeleted\" = false AND \"Status\" != 'Done'");

                    b.HasIndex("LinkedEntityType", "LinkedEntityId")
                        .HasDatabaseName("IX_Tasks_LinkedEntity");

                    b.HasIndex("AssignedToUserId", "Status", "DueDate")
                        .HasDatabaseName("IX_Tasks_AssignedToUserId_Status_DueDate");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdpIssuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdpSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RegionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("IX_UserProfiles_DisplayName");

                    b.HasIndex("IdpIssuer", "IdpSubject")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProfiles_IdpIssuer_IdpSubject");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.WorkflowSlaThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LineOfBusiness")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TargetDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WarningDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "Status", "LineOfBusiness")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowSlaThresholds_EntityType_Status_LineOfBusiness");

                    b.ToTable("WorkflowSlaThresholds", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowSlaThresholds_WarningLessThanTarget", "\"WarningDays\" < \"TargetDays\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("1fef8cb4-2f9b-41e8-9329-3c1a5d22790a"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "Received",
                            TargetDays = 2,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 1
                        },
                        new
                        {
                            Id = new Guid("f6969f8b-7ab9-4ab0-a6e9-26f95f57b21c"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "Triaging",
                            TargetDays = 2,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 1
                        },
                        new
                        {
                            Id = new Guid("379f3ad6-68f0-4d2f-b52f-5ab9bb40f157"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "submission",
                            Status = "WaitingOnBroker",
                            TargetDays = 3,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 2
                        },
                        new
                        {
                            Id = new Guid("30efe68f-9e5c-4e7f-9191-e68ee0f8eb26"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "Identified",
                            TargetDays = 90,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 60
                        },
                        new
                        {
                            Id = new Guid("1e92d4d0-b89a-4b5e-9e01-7d4cf14ed564"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            LineOfBusiness = "Property",
                            Status = "Identified",
                            TargetDays = 90,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 60
                        },
                        new
                        {
                            Id = new Guid("c47d2142-e4b2-4dc3-90c8-3f0da6a07f8b"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            LineOfBusiness = "GeneralLiability",
                            Status = "Identified",
                            TargetDays = 90,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 60
                        },
                        new
                        {
                            Id = new Guid("d7286c4c-38d5-4e57-9837-2b44cf2a86cf"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            LineOfBusiness = "WorkersCompensation",
                            Status = "Identified",
                            TargetDays = 120,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 90
                        },
                        new
                        {
                            Id = new Guid("0ebb7f8c-9709-4b54-a6a4-dcff0b2d3de5"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            LineOfBusiness = "ProfessionalLiability",
                            Status = "Identified",
                            TargetDays = 90,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 60
                        },
                        new
                        {
                            Id = new Guid("d5bc3dd5-17ec-4f56-a8c6-f5b503f17f0d"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            LineOfBusiness = "Cyber",
                            Status = "Identified",
                            TargetDays = 60,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 45
                        },
                        new
                        {
                            Id = new Guid("bb695667-05cf-43dd-a89c-c05e4747967c"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "Outreach",
                            TargetDays = 7,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 3
                        },
                        new
                        {
                            Id = new Guid("77ca3fa9-fddd-47ec-b4d2-84bcbf001687"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "InReview",
                            TargetDays = 14,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 5
                        },
                        new
                        {
                            Id = new Guid("f501f5dd-23d4-4250-9eab-65a70d0c08f5"),
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityType = "renewal",
                            Status = "Quoted",
                            TargetDays = 21,
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningDays = 7
                        });
                });

            modelBuilder.Entity("Nebula.Domain.Entities.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromState")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_WT_EntityId_OccurredAt");

                    b.ToTable("WorkflowTransitions", (string)null);
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Broker", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.MGA", "Mga")
                        .WithMany()
                        .HasForeignKey("MgaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nebula.Domain.Entities.Program", "PrimaryProgram")
                        .WithMany()
                        .HasForeignKey("PrimaryProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mga");

                    b.Navigation("PrimaryProgram");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.BrokerRegion", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany("BrokerRegions")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany("Contacts")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Policy", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Program", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.MGA", "Mga")
                        .WithMany()
                        .HasForeignKey("MgaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mga");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Renewal", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.UserProfile", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Policy", "BoundPolicy")
                        .WithMany()
                        .HasForeignKey("BoundPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Submission", "RenewalSubmission")
                        .WithMany()
                        .HasForeignKey("RenewalSubmissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("AssignedToUser");

                    b.Navigation("BoundPolicy");

                    b.Navigation("Broker");

                    b.Navigation("Policy");

                    b.Navigation("RenewalSubmission");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Submission", b =>
                {
                    b.HasOne("Nebula.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.UserProfile", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nebula.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Broker");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Nebula.Domain.Entities.Broker", b =>
                {
                    b.Navigation("BrokerRegions");

                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
